version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - main
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - setup_remote_docker:
          version: 19.03.13

      - checkout

      - run: echo $DOCKERHUB_USER $DOCKERHUB_PASSWORD $CLIENT_ID_SECRET

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

      - run: export VERSION=$(node -p "require('./package.json').version") && docker build -t sakuru9/music-searcher-api:latest -t sakuru9/music-searcher-api:$VERSION .

      - run: docker login -u=$DOCKERHUB_USER -p=$DOCKERHUB_PASSWORD
      - run: export VERSION=$(node -p "require('./package.json').version") && docker push sakuru9/music-searcher-api:$VERSION
      - run: docker push sakuru9/music-searcher-api:latest
      - run: ssh -t $SSH_USER@henril.com -t ls
