version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - main
    docker:
      - image: node:11.10.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

      - run: export VERSION=$(node -p "require('./package.json').version")

      - run: docker build --build-arg SPOTIFY_BASIC_AUTH=$SPOTIFY_BASIC_AUTH --build-arg LOGIN_REDIRECT_URI=$LOGIN_REDIRECT --build-arg WEB_ORIGIN=$WEB_ORIGIN --build-arg CLIENT_ID_SECRET=$CLIENT_ID_SECRET  . -t sakuru9/music-searcher-api:latest -t sakuru9/music-searcher-api:$VERSION

      - run: docker push sakuru9/music-searcher-api:$VERSION
      - run: docker push sakuru9/music-searcher-api:latest
