version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - main
    docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

    working_directory: ~/repo

    steps:
      - setup_remote_docker:
          version: 19.03.13

      - checkout

      - run: echo $DOCKERHUB_USER $DOCKERHUB_PASSWORD $CLIENT_ID_SECRET

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

      - run: export VERSION=$(node -p "require('./package.json').version") && docker build --build-arg CLIENT_ID_SECRET=$CLIENT_ID_SECRET --build-arg DEPLOYHOST=$DEPLOYHOST --build-arg LOGIN_REDIRECT_URI=$LOGIN_REDIRECT_URI --build-arg SPOTIFY_BASIC_AUTH=$SPOTIFY_BASIC_AUTH --build-arg WEB_ORIGIN=$WEB_ORIGIN -t sakuru9/music-searcher-api:latest -t sakuru9/music-searcher-api:$VERSION .

      - run: export VERSION=$(node -p "require('./package.json').version") && docker push sakuru9/music-searcher-api:$VERSION
      - run: docker push sakuru9/music-searcher-api:latest
